### ISSUE TITLE
difference between quick-install.sh & blastoff.sh

### ISSUE THREAD

**Issue by am0123** [brson/multirust#155]
Hello 

I want to ask about what make the difference between quick-install.sh & blastoff.sh

thank you

**Comment by brson** [comment]
Sorry it took so long to get back to you. There is no difference between the two. They are both maintained for compatibility since both URLs have been supported in the past. I briefly accepted a patch to rename blastoff to quick-install, but that broke existing tools, so had to add blastoff.sh back. Now both are supported :( `quick-install.sh` only existed briefly and it may be that we can delete it again without anybody caring.
