### ISSUE TITLE
Allow installing extra targets for a toolchain for cross-compilation

### ISSUE THREAD

**Issue by huonw** [brson/multirust#20]
E.g. `multirust add-target i686-pc-windows-gnu` could (try to) download a build for that target and install to be usable with the current toolchain.

**Comment by flaper87** [comment]
This sounds like a nice thing to have. I wonder if instead of adding an `add-target` command, we should just add a new cli argument to the existing `update`/`override`/`default` commands. 

Along with this, we should probably change the name of the toolchain directory to something like `$toolchain-$target`. We always construct the target anyway.

**Comment by brson** [comment]
It might make sense to solve this problem upstream so that all 'target' libs are their own installation component. In that scenario when you install 'rust' you get 'rustc', 'cargo', 'rust-docs' and e.g. 'rust-target-x86_64-unknown-linux-gnu', and we can distribute just the target libs for every platform on their own.

**Comment by 0X1A** [comment]
@brson This would be rather useful, any decision or progress on this?

**Comment by alilee** [comment]
Just helping search-engine findability on [cross-compiling and linking core crates](http://stackoverflow.com/questions/28031806/cannot-link-against-core-library-when-cross-compiling)

**Comment by alilee** [comment]
There is a pull for this: #112

**Comment by archshift** [comment]
This can be closed.
